In [7]:
import numpy as np
a = np.array([2, 3, 4])
a


array([2, 3, 4])

In [6]:
a.dtype


dtype('int32')

In [5]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [10]:
a = np.array([1, 2, 3, 4]) 
a

array([1, 2, 3, 4])

In [12]:
# The numpy.array() function expects a single positional argument, typically a list, tuple, or another array-like structure. 



In [13]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

# Printing arrays

In [21]:
a = np.arange(5)  # This is 1d array
print(a)

[0 1 2 3 4]


In [32]:
#2D array
t=np.arange(0,12).reshape(1,12)
t       #cannot reshape array of size 12 into shape (3,3) or (5,3)      but we can make it inot (3,4),(4,3) and (1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [28]:
t=np.arange(12).reshape(4,3)
t


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
t=np.arange(1,13).reshape(1,12)
t


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [43]:
c = np.arange(24).reshape(2,3,4)  # 3d array
print(c)                 #we can print in the no of ways i,e multpiples of 24 like (6,4)(12,2) etc

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [47]:
c = np.arange(24).reshape(2,12)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [48]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [51]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [63]:
a = np.array([10, 100, 1000, 10000]) 
a # this prints array as usual


array([   10,   100,  1000, 10000])

In [64]:
b = np.arange(4) #this will print the array of numbers
b

array([0, 1, 2, 3])

In [65]:
c=a-b
c

array([  10,   99,  998, 9997])

In [69]:
c<1000 # will check the condtion and retunrn the boolean value

array([ True,  True,  True, False])

In [66]:
c**2 

array([     100,     9801,   996004, 99940009])