In [1]:
import numpy as np

# Converting a 1D array into a 2D array 

In [5]:
a = np.array([1, 2, 3, 4, 5,6])
a.shape

(6,)

In [6]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [7]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [8]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [9]:
data = np.array([1, 2, 3])

data[1]

2

In [10]:
data[0:2]

array([1, 2])

In [12]:
data[1:]

array([2, 3])

In [13]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [14]:
print(a[a < 5])

[1 2 3 4]


In [16]:
gt = (a >= 5)
gt

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])